// File generated by the Firebase CLI
// For details on how to set up Firebase in your Flutter project, see:
// https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for different platforms
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // For Android
    return const FirebaseOptions(
      apiKey: 'AIzaSyCutyI_BwchVNT4pMWR_9uEzVQGJvxrDV8',
      appId: '1:710875289780:android:1a8e867b74b7f1e11b5fe1',
      messagingSenderId: '710875289780',
      projectId: 'test-checkout-daff3',
      storageBucket: 'test-checkout-daff3.appspot.com',
    );
  }
}
